### ISSUE TITLE
Won't pull movie listings from plex

### ISSUE THREAD

**Issue by edrock200** [l3uddz/plexarr#5]
Thanks for this awesome tool! Works great with tv shows but I can't get it to work with movies. It sees the library but says it can't pull listings. Does it not work with the upgraded movie library? Either way, thanks again!
Ed

**Comment by Animizio** [comment]
hey, sadly it only worked for tvshows too. for movies (using german library name: Filme) i get this error:

user@cb:~$ /opt/plexarr/plexarr --pvr radarr --library Filme

FTL Failed retrieving items from plex libraries error="failed \"Filme\" plex library items: retrieve library items: []"

**Comment by edrock200** [comment]
I don't think plexarr supports the new upgraded plex movie libraries yet.

**Comment by l3uddz** [comment]
plexarr does support the new movie agent.

i would imagine this is a problem with the library name being provided to plexarr

**Comment by Iguana9999phil** [comment]
Doubt it, testing the latest version and issue is still there with any of my movie libraries. 
Example here:
DBG Retrieved libraries libraries=[{"ID":1,"Name":"Movies","Path":"/home/plex/media/Movies","Type":1}url=http://plex:32400
1:14PM FTL Failed retrieving items from plex libraries error="failed \"Movies\" plex library items: retrieve library items: []"

Could it be an issue with the type? Creating a test Moviestest with type TVShows works.

**Comment by l3uddz** [comment]
this should be resolved in the latest version
