### ISSUE TITLE
[Suggestion] Episode Correction

### ISSUE THREAD

**Issue by meowmix3** [l3uddz/plexarr#8]
Hey!  Really enjoy playing around with Plexarr, thanks for all the work.

Currently my Sonarr setup has renaming disabled, as I typically have it provide the NFO's for metadata.  However, since Plex does not support NFO metadata, the matches are all over the place when it comes with episodes.  The movies seem to work fine without renaming, its just Sonarr & Plex.

Would it be possible to have Plexarr fix the episode matches according to Sonarr/TVDB in a future release?  Currently it just fixes the series matches.

Thanks for reading!

**Comment by ataylor-us** [comment]
I ended up just renaming my library and Plexarr has been working great, so I'm going to close this as its unnecessary.
